// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0WzvkcbZ6cnREOCKVsek4IeeGLvHaGEw',
    appId: '1:772158619240:web:6cc45e00323dc912f585dd',
    messagingSenderId: '772158619240',
    projectId: 'attendancemanagment-7f92c',
    authDomain: 'attendancemanagment-7f92c.firebaseapp.com',
    storageBucket: 'attendancemanagment-7f92c.firebasestorage.app',
    measurementId: 'G-XGDBGWDD5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbjG-IjOg1AtO1_ixOwRnEEhxJRIHNpYs',
    appId: '1:772158619240:android:90b74a051bc95c51f585dd',
    messagingSenderId: '772158619240',
    projectId: 'attendancemanagment-7f92c',
    storageBucket: 'attendancemanagment-7f92c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZjuqDzEIIUF5PKg3iD2XIJov-cwOGYI8',
    appId: '1:772158619240:ios:3825ed95109111ecf585dd',
    messagingSenderId: '772158619240',
    projectId: 'attendancemanagment-7f92c',
    storageBucket: 'attendancemanagment-7f92c.firebasestorage.app',
    iosBundleId: 'com.example.attendancemanagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZjuqDzEIIUF5PKg3iD2XIJov-cwOGYI8',
    appId: '1:772158619240:ios:3825ed95109111ecf585dd',
    messagingSenderId: '772158619240',
    projectId: 'attendancemanagment-7f92c',
    storageBucket: 'attendancemanagment-7f92c.firebasestorage.app',
    iosBundleId: 'com.example.attendancemanagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0WzvkcbZ6cnREOCKVsek4IeeGLvHaGEw',
    appId: '1:772158619240:web:8193e70a5cec9ba2f585dd',
    messagingSenderId: '772158619240',
    projectId: 'attendancemanagment-7f92c',
    authDomain: 'attendancemanagment-7f92c.firebaseapp.com',
    storageBucket: 'attendancemanagment-7f92c.firebasestorage.app',
    measurementId: 'G-B41MG3K57F',
  );
}
